/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "mnsc_data_constants.h"

namespace meituan_mns {

const mnsc_dataConstants g_mnsc_data_constants;

mnsc_dataConstants::mnsc_dataConstants() {
  PROD = "prod";

  STAGE = "stage";

  TEST = "test";

  SUCCESS = 200;

  MNSCache_UPDATE = 500;

  TIMEOUT_ERROR = 400;

  ILLEGAL_ARGUMENT = 400;

  NOT_FOUND = 404;

  NOT_MODIFIED = 304;

}

} // namespace

