/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "mnsc_service_constants.h"

namespace meituan_mns {

const mnsc_serviceConstants g_mnsc_service_constants;

mnsc_serviceConstants::mnsc_serviceConstants() {
}

} // namespace

