/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "naming_service_constants.h"

namespace meituan_mns {

const naming_serviceConstants g_naming_service_constants;

naming_serviceConstants::naming_serviceConstants() {
}

} // namespace

