/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "naming_data_constants.h"

namespace meituan_mns {

const naming_dataConstants g_naming_data_constants;

naming_dataConstants::naming_dataConstants() {
}

} // namespace

