/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "naming_common_constants.h"

namespace meituan_mns {

const naming_commonConstants g_naming_common_constants;

naming_commonConstants::naming_commonConstants() {
}

} // namespace

