// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ServiceAgent.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::meituan_mns;

class ServiceAgentHandler : virtual public ServiceAgentIf {
 public:
  ServiceAgentHandler() {
    // Your initialization goes here
  }

  void getServiceListByProtocol(ProtocolResponse& _return, const ProtocolRequest& req) {
    // Your implementation goes here
    printf("getServiceListByProtocol\n");
  }

  void getOriginServiceList(ProtocolResponse& _return, const ProtocolRequest& req) {
    // Your implementation goes here
    printf("getOriginServiceList\n");
  }

  int32_t registService(const SGService& oService) {
    // Your implementation goes here
    printf("registService\n");
  }

  int32_t registServicewithCmd(const int32_t uptCmd, const SGService& oService) {
    // Your implementation goes here
    printf("registServicewithCmd\n");
  }

  int32_t unRegistService(const SGService& oService) {
    // Your implementation goes here
    printf("unRegistService\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<ServiceAgentHandler> handler(new ServiceAgentHandler());
  shared_ptr<TProcessor> processor(new ServiceAgentProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

