/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftSpans_constants.h"



const ThriftSpansConstants g_ThriftSpans_constants;

ThriftSpansConstants::ThriftSpansConstants() {
}



