/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "unified_protocol_constants.h"

namespace meituan_mns {

const unified_protocolConstants g_unified_protocol_constants;

unified_protocolConstants::unified_protocolConstants() {
}

} // namespace

